import { Logger } from './logger/Logger';
import { CordovaPluginsProvidersManager } from './DEWorkbench/services/CordovaPluginsProvidersManager';
import { ServerManager } from '././DEWorkbench/services/ServerManager';
import { ProjectManager } from './DEWorkbench/ProjectManager';
import { EventBus } from './DEWorkbench/EventBus';
declare const _default: {
    deWorkbench: any;
    toolbarPanel: any;
    subscriptions: any;
    loggerView: any;
    ink: any;
    cordovaPluginsProvidersManager: any;
    activate(state: any): void;
    deferredActivation(): void;
    deactivate(): void;
    showPushTool(): void;
    toggleProjectInspector(): void;
    toggleToolbar(): void;
    toggleLogger(): void;
    consumeInk: (ink: any) => void;
    provideCordovaPluginsProvider(): CordovaPluginsProvidersManager;
    provideLogger(): Logger;
    provideProjectManager(): ProjectManager;
    provideEventBus(): EventBus;
    provideServerManager(): ServerManager;
};
export default _default;
